spring:
  application:
    name: EhCache-Example

  datasource:
    url: jdbc:mysql://localhost:3306/ehcache_db?createDatabaseIfNotExist=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# EhCache CONFIGURATION
  cache:
    jcache:
      config: "classpath:ehcache.xml"

server:
  port: 6000